### ISSUE TITLE
Watch stuck with first compile

### ISSUE THREAD

**Issue by harrypujols** [colynb/gulp-swig#14]
I have a template that compiles fine when I first run the default task, but once it's running, `watch` is stuck, compiling the information that was in the first default run, regardless it changed or was deleted.

This is a basic gulpfile setup to reproduce the issue

``` javascript
var gulp        = require('gulp'),
    swig        = require('gulp-swig');

gulp.task('templates', function() {
  gulp.src('./dev/*.html')
    .pipe(swig())
    .pipe(gulp.dest('./build'))
});

gulp.task('watch', function() {
    gulp.watch('./dev/*.html', ['templates']);
});

gulp.task('default', ['templates', 'watch']);
```

Let's say I have this in `./dev/index.html`:

```
{% set foo = "Bob" %}
<h1>Hello {{foo}}</h1>
```

I run `gulp`,  it compiles to:

```
<h1>Hello Bob</h1>
```

Now, it's running `watch`. I change the data:

```
{% set foo = "Joe" %}
<h1>Hello {{foo}}</h1>
```

`watch` runs as expected, but it compiled to:

```
<h1>Hello Bob</h1>
```

Now I change the file completely, 

```
{% set bar = "Larry" %}
<h1>Hello {{bar}}</h1>
```

I still get

```
<h1>Hello Bob</h1>
```

The file will only compile to `<h1>Hello Larry</h1>` when I stop `watch` and run `gulp` again. Then it will be stuck with compiling `<h1>Hello Larry</h1>`.

**Comment by mrgamer** [comment]
+1 This is an important use case

**Comment by mettjus** [comment]
Had the same problem and used the solution @harrypujols suggested. Looks like the cache kicks in every time after the first compile, caching everything and making it quite useless.. Maybe I'm missing the point, though..

**Comment by Monstroplante** [comment]
+1 I just lost 30min figuring out what happened...
