### ISSUE TITLE
Support Request: loop through array

### ISSUE THREAD

**Issue by frob** [colynb/gulp-swig#34]
Is there a way to loop through an array with this plugin?

EX:
```json
{ "people": [
  { "name": "Pat Doe" },
  { "name": "John Doe" },
  { "name": "Jane Doe" }
]}
```
Given the above json, can it print each of the people in the people array?

**Comment by colynb** [comment]
Just referring to the [swig docs](http://paularmstrong.github.io/swig/), I think what you're looking for is:

```
<ul>
{% for person in people %}
  <li>
    {{ person.name }}
  </li>
{% endfor %}
</ul>
```
