### ISSUE TITLE
JSON variables into simple HTML file

### ISSUE THREAD

**Issue by MartinDM** [colynb/gulp-swig#36]
I feel there's not enough info on the npm page for this Gulp plugin - I could use some help please...

I have a normal HTML file with a tag {{ name }} awaiting to be filled from an info.json file which looks like this:

```javascript
  name: "Martin", 
  campaignName: "New campaign",
  copy: {
    headline: "Welcome",
    subheader: "This is the subheader"
  };
```

My gulp task looks like this which uses the data plugin

```javascript
gulp.task('swig', function() {
  return gulp.src('./src/*.html')
    .pipe(data('./src/info.json'))
    .pipe(swig())
    .pipe(gulp.dest('./build'))
});
```

I may not even need the gulp-data plugin, but I was hoping it'd allow me to easily use a JSON object to populate some basic Swig tags in the HTML...is this the case? Am I referencing it wrongly?

Note: The gulp process errors on the first character in the JSON suggesting it wasn't expecting it...

Any help appreciated! Thanks.

Martin

**Comment by colynb** [comment]
Looks like you're passing the file path to the json file as a parameter but that's not how gulp-data works. It accepts a callback. The first example on gulp-data demonstrates this (modified to match your example):

```
gulp.task('swig', function() {
  return gulp.src('./src/*.html')
    .pipe(data(function(file) {
      return JSON.parse(fs.readFileSync('./src/info.json'));
    }))
    .pipe(swig())
    .pipe(gulp.dest('./build'));
});
```

**Comment by MartinDM** [comment]
Thanks for giving this attention.

I see that the data() method needs to be passed a callback. The example you give has extra elements not in the documented example. Could you explain this line, specifically where the variable ```fs``` is coming from, as this is erroring as fs is not defined.

```javascript
return JSON.parse(fs.readFileSync('./src/info.json'));
```javascript

I'm not there yet, thanks for the help though. On a side note, could the json reference just be stored in a variable and passed into data() with a single word?

Martin
